### PR TITLE
countdown fixed

### LINKED ISSUE #20: CountDown is not working

### PR DESCRIPTION
**Pull request by richardshaju**
fix #20

### CODE REVIEW

File: app/page.tsx [hunk 1]
```diff
@@ -42,20 +42,19 @@ export default function Home() {
     getUpcomingEvents()
```
Comment (chethaslp) [inline app/page.tsx:40]: Use separate useEffect for countdown.
Current approach calls getUpcomingEvents every second, increasing the load on server.

**Review by chethaslp — CHANGES_REQUESTED** [review]

**Comment by richardshaju** [comment]
Done @chethaslp
